services:
  Test\TestBundle\Routing\RestLoader:
    tags: [routing.loader]
    arguments: ['@service_container', '@logger']
#    test.example:
#        class: Test\TestBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
